const ROLES = {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    TEAM_LEAD: 'TEAM_LEAD',
    SENIOR_DEVELOPER: 'SENIOR_DEVELOPER',
    EMPLOYEE: 'EMPLOYEE',
};

const ROLE_PERMISSIONS = {
    [ROLES.SUPER_ADMIN]: [
        'user:create',
        'user:read',
        'user:update',
        'user:delete',
        'user:change-role',
        'project:create',
        'project:read',
        'project:update',
        'project:delete',
        'phase:create',
        'phase:read',
        'phase:update',
        'phase:delete',
        'task:create',
        'task:read',
        'task:update',
        'task:delete',
        'task:assign',
        'team:create',
        'team:read',
        'team:update',
        'team:delete',
        'tag:create',
        'tag:read',
        'tag:update',
        'tag:delete',
        'submission:create',
        'submission:read',
        'review:create',
        'review:read',
        'dashboard:read',
        'activity:read',
    ],
    [ROLES.ADMIN]: [
        'user:read',
        'project:create',
        'project:read',
        'project:update',
        'project:delete',
        'phase:create',
        'phase:read',
        'phase:update',
        'phase:delete',
        'task:create',
        'task:read',
        'task:update',
        'task:delete',
        'task:assign',
        'team:create',
        'team:read',
        'team:update',
        'team:delete',
        'tag:create',
        'tag:read',
        'tag:update',
        'tag:delete',
        'submission:read',
        'review:create',
        'review:read',
        'dashboard:read',
        'activity:read',
    ],
    [ROLES.TEAM_LEAD]: [
        'user:read',
        'project:read',
        'phase:read',
        'task:create',
        'task:read',
        'task:update',
        'task:assign',
        'team:read',
        'tag:read',
        'submission:read',
        'review:create',
        'review:read',
        'dashboard:read',
        'activity:read',
    ],
    [ROLES.SENIOR_DEVELOPER]: [
        'user:read',
        'project:read',
        'phase:read',
        'task:create',
        'task:read',
        'task:update',
        'task:assign',
        'team:read',
        'tag:read',
        'submission:read',
        'review:create',
        'review:read',
        'dashboard:read',
        'activity:read',
    ],
    [ROLES.EMPLOYEE]: [
        'user:read',
        'project:read',
        'phase:read',
        'task:read',
        'task:update',
        'team:read',
        'tag:read',
        'submission:create',
        'submission:read',
        'activity:read',
    ],
};

const hasPermission = (role, permission) => {
    return ROLE_PERMISSIONS[role]?.includes(permission) || false;
};

const canAccessResource = (userRole, requiredRoles) => {
    return requiredRoles.includes(userRole);
};

module.exports = {
    ROLES,
    ROLE_PERMISSIONS,
    hasPermission,
    canAccessResource,
};
